#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /hello-{name}
    controller: App\Controller\DefaultController::index

mail:
    path: /mail
    controller: App\Controller\DefaultController::mail